#!/bin/bash

set -o errexit

USAGE=$'Usage:
  execute-replay [options]

Deploy a one time job to Metronome that executes the latest Docker image of kixi.event-replay passing the relavant args.

Options:
  -s,--start-time        time from which to start the replace, defaults to beginning of the system "20170414T16"
  -e,--end-time          time to replay upto, defaults to processing upto now
  -p,--profile           set of internally configured args to use to communicate with target environment, default staging
  -t,--target-stream     name of kinesis stream, will be created if not exists, to replay the events into
  -v,--version           docker image version, use git-sha version, eg "git-a6f66ec6b7221d42c8fe4d8c9061c69f096642ef"
  -h,--help              this message

Notes:
 -- times should be formatted YYYY-MM-ddTHH
 -- single char options must be followed immediately by the value, eg -s2017-01-01T01
 -- long options must be followed by =value, eg --start-time=2017-01-01T01'

VALID_TIME="20[0-9]{2}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(0[1-9]|1[0-9|2[0-3])"

SYSTEM_START_TIME=

START_TIME="2017-04-14T16"
END_TIME=`date +%Y-%m-%dT%H -u -d "now + 1 hour"`
PROFILE="staging"
TARGET_STREAM=
VERSION=
HELP=0

#read options

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  -h|--help) HELP=1 ; shift ;;
  -s|--start-time) START_TIME=$2 ; shift 2 ;;
  -e|--end-time) END_TIME=$2 ; shift 2 ;;
  -p|--profile) PROFILE=$2 ; shift 2 ;;
  -t|--target-stream) TARGET_STREAM=$2 ; shift 2 ;;
  -v|--version) VERSION=$2 ; shift 2 ;;
  *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters


if [[ "$HELP" -eq 1 ]]; then
   echo "$USAGE";
   exit 1;
fi


if ! [[ "$START_TIME" =~ ^$VALID_TIME ]]; then
   echo "INVALID start time: $START_TIME";
   exit 1;
fi

if ! [[ "$END_TIME" =~ ^$VALID_TIME ]]; then
   echo "INVALID end time: $END_TIME";
   exit 1;
fi

case $PROFILE in
  staging) KINESIS_REGION="eu-central-1"
           KINESIS_ENDPOINT="kinesis.eu-central-1.amazonaws.com"
           S3_BASE_DIR="staging-witan-event-log"
           S3_REGION="eu-central-1"
           ;;
  prod) KINESIS_REGION="eu-west-1"
        KINESIS_ENDPOINT="kinesis.eu-west-1.amazonaws.com"
        S3_BASE_DIR="prod-witan-event-log-20180314"
        S3_REGION="eu-west-1"
        ;;
  *)
    echo "INVALID profile: $PROFILE"
    exit 1
    ;;
esac

if [[ -z "$TARGET_STREAM" ]]; then
  echo "INVALID target kinesis stream must be provided";
  exit 1;
fi

OWNER=`id --name -u`
STREAM_NO_DOT=`echo "$TARGET_STREAM" | tr . -`
JOB_NAME="event-replay.into-$STREAM_NO_DOT-by-$OWNER"

echo "Building Metronome Job definition"

sed -e "s/@@JOB_NAME@@/$JOB_NAME/" \
    -e "s/@@OWNER@@/$OWNER/" \
    -e "s/@@START_TIME@@/$START_TIME/" \
    -e "s/@@END_TIME@@/$END_TIME/" \
    -e "s/@@TARGET_STREAM@@/$TARGET_STREAM/" \
    -e "s/@@KINESIS_ENDPOINT@@/$KINESIS_ENDPOINT/" \
    -e "s/@@KINESIS_REGION@@/$KINESIS_REGION/" \
    -e "s/@@S3_BASE_DIR@@/$S3_BASE_DIR/" \
    -e "s/@@S3_REGION@@/$S3_REGION/" \
    -e "s/@@VERSION@@/$VERSION/" \
    ./deployment/metronome_template.json \
    > metronome.json

echo "Deploying Job $JOB_NAME"
dcos job add metronome.json
echo "Executing Job"
dcos job run $JOB_NAME
